Traceback (most recent call last):
  File "c:\AppsPy\mtdcovabm\simulator\contactnetwork_mp.py", line 163, in contactnetwork_worker
    contact_network_util.simulate_contact_network(day, weekday)
  File "c:\AppsPy\mtdcovabm\simulator\contactnetwork.py", line 68, in simulate_contact_network
    cell_agents_directcontacts, cell = self.simulate_contact_network_by_cellid(cellid, day)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\AppsPy\mtdcovabm\simulator\contactnetwork.py", line 100, in simulate_contact_network_by_cellid
    self.epi_util.simulate_direct_contacts(agents_directcontacts, cellid, cell, day)
  File "c:\AppsPy\mtdcovabm\simulator\epidemiology.py", line 192, in simulate_direct_contacts
    agent_state_transition_by_day, agent_seir_state, agent_infection_type, agent_infection_severity, recovered = self.simulate_seir_state_transition(exposed_agent_id, incremental_days, overlapping_timesteps, agent_state_transition_by_day, agent_epi_age_bracket_index, agent_quarantine_days)
                                                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\AppsPy\mtdcovabm\simulator\epidemiology.py", line 222, in simulate_seir_state_transition
    agent_state_transition_by_day.append([incremental_days, SEIRStateTransition.ExposedToInfectious, sampled_exposed_timestep])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'append'
