Traceback (most recent call last):
  File "C:\AppsPy\mtdcovabm\simulator\itinerary_mp.py", line 206, in localitinerary_worker
    itinerary_util.generate_local_itinerary(day, weekday, hh_inst["resident_uids"])
  File "C:\AppsPy\mtdcovabm\simulator\itinerary.py", line 360, in generate_local_itinerary
    prev_day_last_action, prev_day_last_cell = prev_day_itinerary[prev_day_last_ts]
                                               ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
