Traceback (most recent call last):
  File "C:\AppsPy\mtdcovabm\simulator\sim.py", line 417, in <module>
    itinerary_util.generate_local_itinerary(day, weekday, agents_ids_by_ages, hh_inst["resident_uids"])
  File "c:\AppsPy\mtdcovabm\simulator\itinerary.py", line 1115, in generate_local_itinerary
    (not is_quarantined_or_hospitalised or is_quarantine_hospital_start_day )
TypeError: 'bool' object is not callable
